### ISSUE TITLE
The -Og flag doesn't exist in Clang

### ISSUE THREAD

**Issue by aktau** [tavianator/bfs#1]
Hi, bfs(1) works fine on OSX, except that it doesn't compile with the default compiler:

```
➜  bfs git:(master) ✗ make
cc -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF bfs.d -c bfs.c -o bfs.o
cc -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF bftw.d -c bftw.c -o bftw.o
cc -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF color.d -c color.c -o color.o
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
make: *** [bftw.o] Error 1
make: *** Waiting for unfinished jobs....
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
make: *** [bfs.o] Error 1
make: *** [color.o] Error 1
```

It does work with gcc 5.2

```
➜  bfs git:(master) ✗ CC=gcc-5 make
gcc-5 -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF bfs.d -c bfs.c -o bfs.o
gcc-5 -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF bftw.d -c bftw.c -o bftw.o
gcc-5 -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF color.d -c color.c -o color.o
gcc-5 -D_DEFAULT_SOURCE  -std=c99 -g -Og -Wall -MD -MP -MF bfs  bfs.o bftw.o color.o -o bfs
```

On that note, perhaps it wouldn't be bad to add a `make release` mode. Or, as is better in my experience, let the default `make` target be an optimized build (`-O2 -flto`) and provide a `make debug` target.

If it builds with a regular `make` invocation on OSX, this could get included in homebrew, which would be great.

Very beautiful code too, I enjoyed reading it.

**Comment by tavianator** [comment]
Actually I suspect this would have worked in `brew` before anyway, doesn't it set some `CFLAGS` in the environment?

**Comment by tavianator** [comment]
Oh and,

> Very beautiful code too, I enjoyed reading it.

Thank you! :)

**Comment by aktau** [comment]
> Actually I suspect this would have worked in brew before anyway, doesn't it set some CFLAGS in the environment?

I haven't truly worked out how homebrews "superenv" works, but I'm not so sure it would override your optimization flags. Could be...

At any rate, are you in favour of a release mode (or as I suggested last, a debug mode)?

**Comment by tavianator** [comment]
> At any rate, are you in favour of a release mode (or as I suggested last, a debug mode)?

https://github.com/tavianator/bfs/commit/a47cee3a89da7a2cff6b615e381fd486d5d9c06e :)

I kept debug the default since I don't want to have to rebuild every time I want to use gdb.

**Comment by aktau** [comment]
Awesome, thanks!
