### ISSUE TITLE
Consider removing all nohidden/hidden code

### ISSUE THREAD

**Issue by Earnestly** [tavianator/bfs#11]
Dotfiles are one of those old bugs introduced long ago in an attempt to make `ls` skip the directories `.` and `..` which permeate every directory, and because the code only checked if the first byte was `.`, [[1]](https://plus.google.com/101960720994009339267/posts/R58WgWwN9jp).

It resulted in decades of developer abuse and clutter, including paranoia as now shells ignore these so-called "dotfiles" during globbing operations resulting in data loss as `*` does not mean "matches any string" as the glob(7) manual suggests.

In the name of simplicity, consider removing support for this pointless distinction or at least make the reality of the filesystem (`-nohidden`) the default.

As an aside, this would make `bfs` more compatible with `find`.

*PS: This mechanism was correctly done by GoboLinux with their [gobohide](http://www.gobolinux.org/index.php?page=doc/articles/gobohide) tool and module.*

**Comment by tavianator** [comment]
I'm not sure what you're asking for exactly.  The default behaviour of `bfs` is identical to `find`, i.e. it shows *all* files and directories:

```
$ bfs
./file
./.dotfile
./folder
./.dotfolder
./folder/file
./folder/.dotfile
./.dotfolder/file
./.dotfolder/.dotfile
```

`bfs -nohidden` filters out dotfiles:

```
$ bfs -nohidden
./file
./folder
./folder/file
```

`bfs -hidden` finds *only* dotfiles:

```
$ bfs -hidden
./.dotfile
./.dotfolder
./folder/.dotfile
./.dotfolder/.dotfile
```

Are you really asking me to *remove* this functionality from `bfs`?

**Comment by krhancoc** [comment]
> As an aside, this would make bfs more compatible with find.  

This does not make sense as `find` by default will list hidden and non-hidden files.  So I agree with @tavianator - this already has been implemented identically to find in this manner.

**Comment by Earnestly** [comment]
Ah, I misunderstood what `-no-hidden` was implying.  That said, while I still don't see any value in this code existing, it at least isn't causing my initial issue.  Sorry and thanks for the replies
