### ISSUE TITLE
bfs takes a long time to exit with SIGTERM

### ISSUE THREAD

**Issue by uhthomas** [tavianator/bfs#116]
Interrupting bfs with `CTRL+C` will prevent any further output, but it takes ages to actually exit. In my case I saw it took about 40 seconds.

```sh
❯ bfs -type f /
```

```sh
❯ bfs -version
bfs 3.0.1
```

**Comment by tavianator** [comment]
That's... weird.  Does it happen with -j1?

**Comment by uhthomas** [comment]
It seems a bit better with `-j1`, though I am having a hard time reproducing it consistently. I have a feeling that a very slow rclone fs is the root cause, though I imagine it should still be possible for bfs to abort immediately without waiting for the syscall to finish?

**Comment by tavianator** [comment]
Yeah bfs doesn't normally install any signal handlers or anything (unless you use `-status`), so any delay is probably in the kernel as it tears down the process.

Does the same thing happen with `find`?  If not, does it still happen with `bfs` if you set a lower open file limit (e.g. `ulimit -Hn 1024`)?

**Comment by tavianator** [comment]
I'm going to close this for now, let me know if you're able to reproduce it again and try the suggestions from the previous comment
