### ISSUE TITLE
Feature request for static build

### ISSUE THREAD

**Issue by adsr** [tavianator/bfs#117]
Would be nice if the Makefile supported a fully static build

**Comment by tavianator** [comment]
`make LDFLAGS="-static"` should work

**Comment by aauren** [comment]
Just updating here. This worked for me for a while, but recently stopped working.

I was able to fix it by changing `-static` to the `./configure` command instead of the `make` command.

```
./configure LDFLAGS="-static"
make
```

**Comment by tavianator** [comment]
True.  Actually I'd recommend

```console
$ ./configure EXTRA_LDFLAGS="-static"
```

to not clobber any other `LDFLAGS`.
