### ISSUE TITLE
paths which contain '.' or '..'

### ISSUE THREAD

**Issue by chapmanjacobd** [tavianator/bfs#124]
I have found some strangeness when bfs encounters a folder that has '.' or '..' in its path.

For example I have these folders:

```shell
/tmp/Soundcloud/.ION./
/tmp/Soundcloud/.._Shok_../
```

They are empty. but when I run this:

```fish
yes | bfs -nohidden -type d -exec bfs -f {} -not -type d -exit 1 \; -prune -ok bfs -f {} -type d -delete \;
```

the folders aren't deleted

**Comment by tavianator** [comment]
Those folders are hidden, so `-nohidden` filters them out
