### ISSUE TITLE
cjk characters cannot be displayed correctly

### ISSUE THREAD

**Issue by lost22git** [tavianator/bfs#128]
![Screenshot 2023-12-15 101523](https://github.com/tavianator/bfs/assets/65008815/37f2220c-bca3-4b73-9215-944b6f45e6c9)

**Comment by tavianator** [comment]
Sorry about that!  Can you paste the output of the `locale` command for me?

**Comment by lost22git** [comment]
```
❯ bfs ./Desktop/bqb -name '*截图*'
./Desktop/bqb/$'\xE5\xB1\x8F\xE5\xB9\x95\xE6\x88\xAA\xE5\x9B\xBE 2021-12-25 103614.png'
./Desktop/bqb/$'\xE5\xB1\x8F\xE5\xB9\x95\xE6\x88\xAA\xE5\x9B\xBE 2022-02-10 205237.png'
./Desktop/bqb/$'\xE5\xB1\x8F\xE5\xB9\x95\xE6\x88\xAA\xE5\x9B\xBE 2022-04-01 033635.png'
./Desktop/bqb/$'\xE5\xB1\x8F\xE5\xB9\x95\xE6\x88\xAA\xE5\x9B\xBE 2022-10-14 081805.png'
./Desktop/bqb/$'\xE5\xB1\x8F\xE5\xB9\x95\xE6\x88\xAA\xE5\x9B\xBE 2022-10-22 033037.png'
```

**Comment by tavianator** [comment]
Hmm okay I tried those filenames locally and they work for me, so this is probably a platform-specific bug.  Can you please tell me

- What version of `bfs` you're using?
- How you installed it?
- What operating system (including version) you're using?

Thanks!

**Comment by lost22git** [comment]
@tavianator 

bfs version: 3.0.4
installed by: nix-env
os: Debian 12 (WSL2)

**Comment by tavianator** [comment]
I think the issue is that Nix packages won't use system locale information by default.  https://nixos.wiki/wiki/Locales says to do

```console
$ export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive
```

which fixed it for me in a similar environment to yours (Nix on Debian 12 on Docker).

To use Nix's locale data rather than Debian's, this worked instead:

```console
$ nix-env -iA nixpkgs.glibcLocales
$ export LOCALE_ARCHIVE=/nix/store/ghvznirxqkw0f2wnbmgfk7i70igz66b4-glibc-locales-2.38-27/lib/locale/locale-archive
$ bfs ~/foo
/home/user/foo
/home/user/foo/屏幕截图 2021-12-25 103614.png
```

---

Anyway, whether `bfs` should behave like this when locale data is missing is a good question.  The goal is to avoid printing control characters to the terminal that may do dangerous things.  Currently it checks `isprint()`/`iswprint()` to determine what's safely printable.

**Comment by tavianator** [comment]
> Anyway, whether `bfs` should behave like this when locale data is missing is a good question. The goal is to avoid printing control characters to the terminal that may do dangerous things. Currently it checks `isprint()`/`iswprint()` to determine what's safely printable.

I just checked and GNU find does pretty much the same thing (they use `wcwidth(c) >= 0` which is close enough).  If you run GNU find without locale data, you'll get

```console
$ find foo
foo
foo/???????????? 2021-12-25 103614.png
```

As of https://github.com/tavianator/bfs/commit/023482caa20c0d3b5ab1641f26d8384829b1e43f we'll print a warning if setting the locale fails, which should help.  I think that's about as much of a fix as possible.
