### ISSUE TITLE
Support `max-results`

### ISSUE THREAD

**Issue by SPiCaRiA** [tavianator/bfs#133]
Hi, `bfs` is indeed a great one, especially when working with interactive tools like `fzf`, thank you for crafting this!

It would be even better if we can have a "limit the number of search results and quit when the cap is reached" flag like `--max-results` in `fd`. I believe it will be a game changing feature that can boost the performance for the `bfs❤️fzf` scenarios! 😄

**Comment by tavianator** [comment]
Thanks!  I wrote bfs specifically for using it with fzf, so I'm glad to see others appreciate the synergy :)

I'm not opposed to a `-max-results` option.  You can use `bfs ... | head -n10` to accomplish something similar, but there are caveats, as laid out in https://github.com/sharkdp/fd/issues/472.

However, with `bfs`, I'd need to think a bit about exactly what a "result" is.  `bfs` (like `find`) supports multiple actions per file, controlled by different tests.  If only some of those actions run, is that a "result" or not?  For example:

```console
$ bfs -print -name '*.txt' -print -name 'foo*'
./not-match
./not-foo.txt
./not-foo.txt
./foo.txt
./foo.txt
```

Here, `not-match` was printed only once, because it doesn't pass the next test.  `not-foo.txt` is printed twice, so it seems more like a result that should count.  But only `foo.txt` actually matches the entire expression!  The trailing `-name 'foo*'` doesn't control any actions, so normally it wouldn't have an effect.  But technically, it does affect whether the entire expression returns true or false.

**Comment by SPiCaRiA** [comment]
> Thanks! I wrote bfs specifically for using it with fzf, so I'm glad to see others appreciate the synergy :)

❤️ 

> I'm not opposed to a `-max-results` option. You can use `bfs ... | head -n10` to accomplish something similar, but there are caveats, as laid out in [sharkdp/fd#472](https://github.com/sharkdp/fd/issues/472).

Yeah this is what I'm currently doing as well

> However, with `bfs`, I'd need to think a bit about exactly what a "result" is. `bfs` (like `find`) supports multiple actions per file, controlled by different tests. If only some of those actions run, is that a "result" or not? For example:
> 
> ```
> $ bfs -print -name '*.txt' -print -name 'foo*'
> ./not-match
> ./not-foo.txt
> ./not-foo.txt
> ./foo.txt
> ./foo.txt
> ```
> 
> Here, `not-match` was printed only once, because it doesn't pass the next test. `not-foo.txt` is printed twice, so it seems more like a result that should count. But only `foo.txt` actually matches the entire expression! The trailing `-name 'foo*'` doesn't control any actions, so normally it wouldn't have an effect. But technically, it does affect whether the entire expression returns true or false.

Hmm, (my two cents tho) I think this falls into another (and more complicated) scenario. Just my PO, the use of `bfs` into can be categorized into two:
1. **Cap the end results only**: for example, when used with `fzf`, `bfs` is mostly just a search list producer, in which we don't really care about the actions/tests on the fly. In such case, a `max-results` flag capping the final printed lines is good enough
2. **Cap the actions/tests** (where your concern falls into): this might happen when `bfs` is used as an alternate to `find` on various tasks, such as using `exec` instead of `print` etc.

Case 1 is straightforward, but case 2 needs lot more discussion (which I think may result in many other flags besides `max-results`).

In case 2, we are essentially talking about performance control on a higher granularity (how you control) and more context-specific (what you can control):
1. **A how-you-control example**: limit the number of files that pass all tests/at least one test/etc.
2. **A what-you-can-control example**: limit the total number of actions

At the end of the day we might not want to get our hands wet on case 2 anyway 🤣 So I think `max-results` (or maybe a better name like `max-printed-lines`) is so far so good

**Comment by tavianator** [comment]
> In such case, a `max-results` flag capping the final printed lines is good enough

Yeah, that may be enough for most cases.  (Small corner case: what if the filename contains a newline?  Can we quit half-way through printing a path?)

But I just realized there is a semantically nice way to do case 2: a new action that quits once it gets evaluated a number of times.

```console
$ bfs -type f -name '*foo*' -print -limit 4
```

By placing it after the `-print`, we get the right behaviour: immediate exit after printing any 4 paths.  It's a bit unfortunate that

```console
$ bfs -type f -name '*foo*' -limit 4 # implicit -print
```

wouldn't do the right thing though (it would be similar to `bfs | head -n3`).  But I could add a warning for that case.  What do you think?

**Comment by SPiCaRiA** [comment]
> > In such case, a `max-results` flag capping the final printed lines is good enough
> 
> Yeah, that may be enough for most cases. (Small corner case: what if the filename contains a newline? Can we quit half-way through printing a path?)

I prob should clarify a bit here, by saying "capping the final printed lines" I mean the number of paths printed 🤣

> 
> But I just realized there is a semantically nice way to do case 2: a new action that quits once it gets evaluated a number of times.
> 
> ```
> $ bfs -type f -name '*foo*' -print -limit 4
> ```
> 
> By placing it after the `-print`, we get the right behaviour: immediate exit after printing any 4 paths. It's a bit unfortunate that
> 
> ```
> $ bfs -type f -name '*foo*' -limit 4 # implicit -print
> ```
> 
> wouldn't do the right thing though (it would be similar to `bfs | head -n3`). But I could add a warning for that case. What do you think?

Yeah I do like the `-limit` idea! It now works perfectly for the `max-results` purpose. But I think we're having some problems when setting `-limit` for more than one actions:

```
$ bfs . -mindepth 1 -type f -print -limit <A> -o -type d -print -limit <B>
```

**Expected**: print `A` files and `B` directories
**Got**: very random results. When `A=5` and `B=3` I got 5 files and 1 dirs printed, and when `A=7` and `B=3` I got 5 files and 3 dirs, no idea where they came from :x (I'm fully sure that my cwd has many files and dirs for the search intent)

Anyways I don't need to limit multiple actions so I'm happy to live with it so far, thank you for your work! <3

**Comment by tavianator** [comment]
> Expected: print A files and B directories

Well, this expectation is wrong.  You will get A files ***or*** B directories, whichever comes first, because `-limit` quits the whole search as soon as it triggers.
