### ISSUE TITLE
BSD find compatibility

### ISSUE THREAD

**Issue by tavianator** [tavianator/bfs#14]
Options:
- [x] `-E`
- [x] `-H`
- [x] `-L`
- [x] `-P`
- [x] `-X`
- [x] `-d`
- [x] `-s`
- [x] `-x`
- [x] `-f PATH`

Expressions:
- [x] `( EXPR )`
- [x] `! EXPR`, `-not EXPR`
- [x] `EXPR1 EXPR2`, `EXPR1 -a EXPR2`, `EXPR1 -and EXPR2`
- [x] `EXPR1 -o EXPR2`, `EXPR1 -or EXPR2`

Primaries:

- [x] `-Bmin`, `-Bnewer`, `-Btime`
- [x] `-acl`
- [x] `-anewer`, `-amin`, `-atime`
- [x] `-cnewer`, `-cmin`, `-ctime`
- [x] `-asince`, `-csince`, `-since`
- [x] `-delete`
- [x] `-depth`
- [x] `-depth N`
- [x] `-empty`
- [x] `-exec COMMAND ;`
- [x] `-exec COMMAND {} +`
- [x] `-execdir COMMAND`
- [x] `-execdir COMMAND {} +`
- [x] `-exit STATUS`
- [ ] `-flags FLAGS`
- [x] `-fstype TYPE`
- [x] `-gid GNAME`
- [x] `-group GNAME`
- [x] `-ignore_readdir_race`, `-noignore_readdir_race`
- [x] `-ilname PATTERN`
- [x] `-iname PATTERN`
- [x] `-inum N`
- [x] `-ipath PATTERN`, `-iwholename PATTERN`
- [x] `-iregex PATTERN`
- [x] `-links N`
- [x] `-lname PATTERN`
- [x] `-ls`
- [x] `-maxdepth LEVELS`
- [x] `-mindepth LEVELS`
- [x] `-mnewer`
- [x] `-mmin`, `-mtime`
- [x] `-mount`
- [x] `-name PATTERN`
- [x] `-newer FILE`
- [x] `-newerXY REFERENCE`
- [x] `-nogroup`
- [x] `-nouser`
- [x] `-noleaf`
- [x] `-ok COMMAND ;`
- [x] `-okdir COMMAND ;`
- [x] `-path PATTERN`, `-wholename PATTERN`
- [x] `-perm -?MODE`
- [x] `-perm +MODE`
- [x] `-print`
- [x] `-print0`
- [x] `-printx`
- [x] `-prune`
- [x] `-quit`
- [x] `-regex PATTERN`
- [x] `-rm`
- [x] `-samefile FILE`
- [x] `-size N[ckMGTP]`
- [x] `-sparse`
- [x] `-type [bcdpfls]`
- [x] `-uid UNAME`
- [x] `-user UNAME`

**Comment by grahamperrin** [comment]
<https://www.freshports.org/sysutils/bfs/>

Rocking. Thank you.
