### ISSUE TITLE
A -type flag

### ISSUE THREAD

**Issue by aktau** [tavianator/bfs#2]
I'd like to use this in some `fzf` contraption of mine. Yet for that I would need it to output only directories. For example like the `type d` flag commonly found in `find`.

Since you expose the `typeflag` parameter to the callback but don't do anything with it I assume you wanted to do this but didn't have the time.

The change is at any rate small (37+, 2- lines), I have a patch ready but cannot contribute to your project if it's under the WTFPL . Licenses like MIT/BSD/ISC/Apache 2 or similar would be fine, should you consider changing your license or dual-licensing the project.

I'm not asking you to change the license, that's your prerogative. But if you can't/won't do that, would you perhaps consider adding the feature yourself?

**Comment by tavianator** [comment]
Definitely plan to do this.  But `find` expressions can be a lot more complicated than just `-type d` (e.g. `find -path '*/\\.*' -prune -o -type f -print`), and I want to implement the full grammar.

If I re-license to a more "serious" license it would be Apache 2.

**Comment by aktau** [comment]
I guess the full grammar would be nice for those who have use of it, but the `-type` flag in itself is already useful and has a minimal impact on the code. While I suppose a full fledged find grammar parser and executor will easily reach another 100 lines of code if not more.

At any rate, both things are more or less orthogonal, it seems to me, the `type` flag can be supported without the full grammar.

> If I re-license to a more "serious" license it would be Apache 2.

Apache 2 is a good license. As I said, any of those (all OSI licenses...) would allow me to submit patches, if so desired.

**Comment by aktau** [comment]
Hi Tavian! I don't mean to be a bore, but have you thought about either accepting contributions or adding a simple type check in the callback? My fingers always hurt when I'm at home :).

**Comment by tavianator** [comment]
Sorry, I've been super busy recently!  But I'll have time to get back to this this weekend :)

**Comment by aktau** [comment]
No pressure at all, I know what that's like, take it easy and I'll wait patiently.

**Comment by aktau** [comment]
Thanks a lot!

**Comment by tavianator** [comment]
Hey @aktau sorry to bump this old thread, but I figured I'd let you know that I've [re-licensed](https://github.com/tavianator/bfs/commit/590c038630d453b3652b33e54b81fd06ceb0c6d2) the project under the [0BSD license](https://spdx.org/licenses/0BSD.html), which should be functionally the same but [OSI approved](https://opensource.org/licenses/FPL-1.0.0).

**Comment by aktau** [comment]
>  Hey @aktau sorry to bump this old thread, but I figured I'd let you know that I've re-licensed the project under the 0BSD license, which should be functionally the same but OSI approved.

Good to hear, thanks!
