### ISSUE TITLE
Requires -lrt switch

### ISSUE THREAD

**Issue by kaushalmodi** [tavianator/bfs#29]
Hello,

I just tried compiling this project.

It compiles if I do

```
make CFLAGS+=-lrt
```

Without that, I get

```
eval.c:858: undefined reference to `clock_gettime'
```

**Comment by tavianator** [comment]
I didn't realise how recently that was moved out of librt, will fix.

**Comment by tavianator** [comment]
Sadly there are some portability issues; macOS doesn't have librt, so I can't just add `-lrt` unconditionally to the build.  I've been hoping to avoid autoconf-style checks, but I'm not sure how else to support pre-2.17 glibc.

**Comment by kaushalmodi** [comment]
This is a nice light application.. Might be enough to mention in the README (for now?) that if the user sees:

> eval.c:858: undefined reference to `clock_gettime'

do `make CFLAGS+=-lrt` instead of just `make`.
