### ISSUE TITLE
Not available via apt-get

### ISSUE THREAD

**Issue by haakenlid** [tavianator/bfs#33]
The readme says that bfs is available with apt-get

> If you're on Debian GNU/Linux, bfs is available via `apt-get install bfs.`

But when I try to install it, It doesn't seem to be available. 

```
$ sudo apt-get update && sudo apt-get install bfs
Hit:1 http://archive.ubuntu.com/ubuntu zesty InRelease
Hit:2 http://archive.ubuntu.com/ubuntu zesty-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu zesty-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bfs
```

Using `apt search bfs` does not show any matches either.

**Comment by tavianator** [comment]
It's only in the latest versions.  It should be in Ubuntu 17.10, and Debian testing/unstable.  You can check the [Debian](https://tracker.debian.org/pkg/bfs) and [Ubuntu](https://launchpad.net/ubuntu/+source/bfs) trackers for what versions it appears in.

**Comment by haakenlid** [comment]
If I understand that link correctly it's not available for versions before Ubuntu 17.10 which was released yesterday? Do I need to enable `universe` as well, or is bfs in the default repos?

**Comment by tavianator** [comment]
Not an Ubuntu user so I don't really know!  But the [Ubuntu](https://launchpad.net/ubuntu/+source/bfs) link above says "release (universe)" so I imagine you might have to enable `universe`.

**Comment by haakenlid** [comment]
Ok. Thanks 👍
