### ISSUE TITLE
Permission Issue 

### ISSUE THREAD

**Issue by c3dev** [tavianator/bfs#36]
When it try to list directories inside directory without read permissions, it throws out error. I think `bfs` should skip such directories  before hand.

```
error: './cache/private': Permission denied
error: './cache/ldconfig': Permission denied
error: './db/sudo': Permission denied
error: './tmp/systemd-private-b0c63c239a4f49ebaf5fa0ee80d157c8-ModemManager.service-ODCouH': Permission denied
error: './tmp/systemd-private-b0c63c239a4f49ebaf5fa0ee80d157c8-systemd-timesyncd.service-Jze1lA': Permission denied
error: './lib/portables': Permission denied
error: './lib/machines': Permission denied
error: './lib/private': Permission denied
error: './lib/NetworkManager': Permission denied
error: './lib/udisks2': Permission denied
error: './lib/rpcbind': Permission denied
error: './log/private': Permission denied
error: './spool/cups': Permission denied
error: './lib/nfs/sm': Permission denied
error: './lib/nfs/sm.bak': Permission denied
error: './lib/sddm/.nv': Permission denied
error: './lib/sddm/.config': Permission denied
error: './lib/gssproxy/rcache': Permission denied
```

**Comment by tavianator** [comment]
bfs tries to be compliant with the POSIX spec for `find`.  That includes exiting with an error code if any part of the directory hierarchy was unable to be traversed.  I think it would be very confusing if bfs would exit unsuccessfully without printing the relevant errors so the user can see why if failed.  (On the other hand, if these are errors that `find` isn't printing, that may be a bug.  Let me know if that's what's happening.)

You could suppress those errors with

    bfs ! type d -o -readable -o -prune

which avoids descending into non-readable directories.
