### ISSUE TITLE
Latest bfs version fails to find libacl and libcap

### ISSUE THREAD

**Issue by yermulnik** [tavianator/bfs#39]
```
> LANG=C git pull
Already up to date.

> LANG=C make
[…]
cc -D__EXTENSIONS__ -D_ATFILE_SOURCE -D_BSD_SOURCE -D_DARWIN_C_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DBFS_VERSION=\"1.3\"  -std=c99 -g -Wall -Wmissing-declarations -MD -MP -MF bfs  -Wl,--as-needed  bftw.o color.o diag.o dstring.o eval.o exec.o main.o mtab.o opt.o parse.o posix1e.o printf.o spawn.o stat.o typo.o util.o  -lacl -lcap -lrt  -o bfs
/usr/bin/ld: cannot find -lacl
/usr/bin/ld: cannot find -lcap
collect2: error: ld returned 1 exit status
make: *** [bfs] Error 1

> uname -srm
Linux 4.4.0-119-generic x86_64
```

**Comment by tavianator** [comment]
bfs 1.3 now requires libacl and libcap on Linux.  What distribution are you running?  On Debian/Ubuntu, the relevant packages are `acl-dev` and `libcap-dev`.  On Arch, simply `acl` and `libcap`.  Probably similar elsewhere.

**Comment by yermulnik** [comment]
Oh, thanks for the hint. I've installed missing packages and `bfs` build was successful =)

**Comment by yermulnik** [comment]
For those who come across this (inc again as I do): `apt install libacl1-dev`

**Comment by tavianator** [comment]
You can also find this documented in the "... you may need to install some dependencies" section of https://github.com/tavianator/bfs#installation :)

**Comment by yermulnik** [comment]
> These dependencies are technically optional, though strongly recommended. 
> These dependencies are optional

I'd expect builds with default parameters to not fail because of optional deps =) This includes installs with Homebrew, which one don't typically customize. E.g. https://github.com/tavianator/homebrew-tap/issues/3
