### ISSUE TITLE
Support NO_COLOR

### ISSUE THREAD

**Issue by Earnestly** [tavianator/bfs#55]
While `bfs -nocolor` exists it would perhaps be nice if it honoured (`NO_COLOR`)[https://no-color.org/] to provide a more universal way to prevent the use of colours.

**Comment by Earnestly** [comment]
Oh it appears bfs already supports this: https://github.com/tavianator/bfs/blob/master/parse.c#L3397

I couldn't find any reference to this in the manual and assumed it wasn't supported.
l

**Comment by tavianator** [comment]
You're right that it's not documented, I should do that.
