### ISSUE TITLE
Test fails with "mkdir: 0123456789ABCDEF[...]: Operation not permitted

### ISSUE THREAD

**Issue by ryandesign** [tavianator/bfs#63]
Hello,

testing bfs 2.0 fails for me on macOS 10.13.6.

```
./tests.sh --bfs="/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-svn-trunk_sysutils_bfs/bfs/work/tavianator-bfs-4d98dc6/bfs -S bfs"
mkdir: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDE: Operation not permitted
```

**Comment by tavianator** [comment]
Strange.  I don't have a Mac to test on locally, but the Travis tests pass on macOS 10.13.6: https://travis-ci.org/github/tavianator/bfs/jobs/735782146

Can you run these commands for me, from a git clone of `bfs`, to see where it's failing?

```
$ make all
$ bash -c "set -x; . ./tests.sh --verbose"
```

**Comment by ryandesign** [comment]
With some further experimentation, I see that the tests do complete when I run them "normally" as you suggested.

Originally, I was running the tests within MacPorts, where they failed. I haven't yet figured out which difference about that environment is affecting the tests here.

MacPorts sets a different (longer) value for TMPDIR, but I tried some other values for TMPDIR myself outside of MacPorts and couldn't reproduce the failure.

Here's a log of the failure within MacPorts when I modify it to run the tests with `--verbose` and `set -x`:

https://gist.github.com/ryandesign/721180045372c29b91c73d038b67badd

**Comment by tavianator** [comment]
Does it work if you set `TMPDIR=/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-svn-trunk_sysutils_bfs/bfs/work/.tmp` but run it outside of macports?

If so, it must be some other environmental difference.  Maybe a different `bash`, `mkdir`, environment variables, etc.?

**Comment by tavianator** [comment]
Does macports use any kind of sandbox while building or running tests?  I've had issues with Homebrew for that reason.

I see macports has a "trace" feature.  Is it active?  It looks like it [might not support](https://github.com/macports/macports-base/blob/a494d3e1dee9868770472a64513bf35827fa955d/src/darwintracelib1.0/darwintrace.c#L740) paths longer than `PATH_MAX`, which is what that test is trying to make.

**Comment by tavianator** [comment]
I'm labeling this downstream/wontfix, since it appears to be a macports limitation that's causing the issue.  If I'm wrong, please let me know and I'll reopen this.  Thanks!
