### ISSUE TITLE
bftw(): Permission denied

### ISSUE THREAD

**Issue by simonbcn** [tavianator/bfs#7]
Arch Linux 64 bits
bfs 0.70 (_installed from AUR_)

When I execute a search in system folders, it shows the error `bftw(): Permission denied`. 
Example:
```
$ bfs /usr > /dev/null 
'/usr/share/polkit-1/rules.d/': Permission denied
bftw(): Permission denied
```

**Comment by tavianator** [comment]
Indeed, but

    $ find /usr > /dev/null
    find: `/usr/share/polkit-1/rules.d': Permission denied

Are you talking about the duplicate error message?  I could get rid of that, yeah.

**Comment by simonbcn** [comment]
I refer to this error: `bftw(): Permission denied`. `find` command doesn't show this message.
