### ISSUE TITLE
macOS no color help

### ISSUE THREAD

**Issue by grylem** [tavianator/bfs#76]
Hi
bfs -help
ESC[01;36m-PESC[0m etc. instead color
Regards.

**Comment by tavianator** [comment]
Thanks for the report.  Did this work with the previous version (2.2)?  Can you tell me the output of

```shell
echo $PAGER
echo $LESS
```

**Comment by grylem** [comment]
> Did this work with the previous version (2.2)?

No. The old version has the same problems

echo $PAGER
nothing
echo $LESS
-R

**Comment by tavianator** [comment]
Ah okay.  `bfs` doesn't override `LESS` because if it's explicitly set, it might have flags that are necessary to make it work right on a particular terminal or something.  If you do `LESS= bfs -help` it should set the right flags.

This is the same behaviour as `git` by the way.  If `git log` etc. have colors for you, maybe you have `pager` set to something in your `~/.gitconfig`?

**Comment by tavianator** [comment]
Hmm actually `LESS=-R` should work.  I'll see if I can get access to a mac to reproduce.  Does `LESS=FKRX bfs -help` work?  What about `LESS=R bfs -help`?

**Comment by grylem** [comment]
> maybe you have pager set to something in your ~/.gitconfig?

no

> LESS=FKRX bfs -help, LESS=R bfs -help

change shell from bash to sh, ksh(without shrc etc.), update less from macports version 581 - with the same result.

**Comment by tavianator** [comment]
Oh wait a second, what about with `PAGER=less`?

**Comment by grylem** [comment]
PAGER=less bfs -help
it works fine

**Comment by tavianator** [comment]
Ah okay.  So what's going on is by default `bfs` actually uses `more` since it's a POSIX utility, whereas `less` might not be installed.  I guess the `more` on macOS escapes the escape sequences, unlike on Linux.  I can reproduce this on FreeBSD too, so I should be able to fix it.

**Comment by grylem** [comment]
it is very good.
Also for old macOS clang(High Sierra Apple LLVM version 10.0.0 (clang-1000.11.45.5)) i have a lot of warnings like
warning: declaration does not declare anything [-Wmissing-declarations]

**Comment by tavianator** [comment]
Hmm can you paste one of the warnings in its entirety?

**Comment by grylem** [comment]
eval.c:241:3: warning: declaration does not declare anything [-Wmissing-declarations]
                fallthrough;
                ^
./util.h:98:22: note: expanded from macro 'fallthrough'
\#       define fallthrough __attribute__((fallthrough))
                           ^
eval.c:244:3: warning: declaration does not declare anything [-Wmissing-declarations]
                fallthrough;
                ^
./util.h:98:22: note: expanded from macro 'fallthrough'
\#       define fallthrough __attribute__((fallthrough))

**Comment by tavianator** [comment]
https://github.com/tavianator/bfs/commit/41c148c4bf835fca788e6990cb8ea8651bb55927 should fix the warnings
