### ISSUE TITLE
macOS: difference between bfs and find with primaries -ls

### ISSUE THREAD

**Issue by grylem** [tavianator/bfs#77]
Hi
echo file >file
find . -ls and ls -s
Display the same values for the number of file system blocks actually used by file - 8, but bfs -ls show - 4.
Regards.

**Comment by tavianator** [comment]
Indeed, the traditional block size is 512 bytes, but bfs follows GNU find here and uses 1KiB blocks.  GNU find's `-ls` will use 512B blocks if `POSIXLY_CORRECT` is set, even though `-ls` is not POSIX.  bfs doesn't listen to POSIXLY_CORRECT about this, but it probably should.
