### ISSUE TITLE
Cargo install?

### ISSUE THREAD

**Issue by deadcoder0904** [tavianator/bfs#78]
I am new to Rust but I try to use its packages like `fd`, `kondo`, `pastel`, `dust` using `cargo install`.

Is there a reason `cargo` is not supported for `bfs`?

**Comment by tavianator** [comment]
`bfs` is written in C, not Rust :)

**Comment by deadcoder0904** [comment]
Hot damn! I came here through following some Rust developers packages. Thought this was Rust executable too haha :)

Is there any way to install C executables on Windows so they are accessed from anywhere? Or just `make`?

**Comment by tavianator** [comment]
I doubt bfs will compile on Windows, it uses too much of the POSIX API.  It will work in WSL, and maybe Cygwin or MSYS.

**Comment by deadcoder0904** [comment]
Cool, nice work anyway :)
