### ISSUE TITLE
[Feature request] Grep style directory exclusion

### ISSUE THREAD

**Issue by bag-man** [tavianator/bfs#8]
I've been using bfs for a while now, it is excellent. One thing that find is terrible for is excluding directories, and I thought maybe bfs could add on a more use friendly system.

It would be a lot nicer if there was the option to exclude/include directories/files in the same way that grep does:

```
--exclude-dir={build,vendor,.git,node_modules} --include=*.{css,vcl,conf,yml,jade,js,styl,php,config,html} --exclude={*.min.js,tags,json}
```

I'd be quite interested in helping to write this functionality, but I thought I would raise it as an issue first to see what your thoughts on it are.

**Comment by tavianator** [comment]
So the `find` analogues of those are:

    # --include=*.css
    -name '*.css'

    # --exclude=*.min.js
    ! -name '*.min.js'

    # --exclude-dir=.git
    ! -name .git -o -prune -false

I think the first two are fine, but the last one is totally unreasonable.  I think the right approach would be:

    -exclude .git

which would prune anything named `.git` without printing it.  `-nohidden` would be equivalent to `-exclude '.?*'`.

Another thing that's nicer with the `grep` syntax you give is giving multiple patterns:

    # --include=*.{css,vcl,...}
    -name '*.css' -o -name '*.vcl' -o ...

Much more compact with the brace-expansion.  `FNM_EXTMATCH` would let you do this at least:

    -name '+(*.css|*.vcl|...)'

**Comment by tavianator** [comment]
Actually `-name .git -exclude` would be a bit more powerful and consistent with `-prune`.  Basically it would do what people expect `-prune` to do.

**Comment by tavianator** [comment]
Oh damn, `-name .git -exclude` won't work.  If `-name .git` returns false then the predicate short-circuits and `-exclude` won't even run.

**Comment by tavianator** [comment]
@bag-man The https://github.com/tavianator/bfs/tree/exclude branch implements this syntax:

    bfs -exclude -name .git

What do you think?

**Comment by bag-man** [comment]
@tavianator Nice one, although I noticed that this worked:

``` bfs -exclude -name node_modules -name package.json```

But this didn't:

```bfs -name package.json -exclude -name node_modules```

Which is a little confusing.

**Comment by merwok** [comment]
Throwing another idea here: I’ve recently started using [ag (the silver searcher)](https://github.com/ggreer/the_silver_searcher), a grep replacement that looks for a .gitignore file for patterns to ignore.  There is also a command-line option to add ignores.

ag replaces a bunch of grep aliases that I was using to look for things in codebases and it would be amazing to have bfs be a similar better replacement for good old inflexible find.
