### ISSUE TITLE
Fix FreeBSD build after ONIGURUMA ON

### ISSUE THREAD

**Issue by driesmp** [tavianator/bfs#82]
Seems like we are missing some include dirs on FreeBSD.
I would expect to see -I /usr/local/include somewhere.

**Comment by driesmp** [comment]
[bfs-2.4.log](https://github.com/tavianator/bfs/files/8127590/bfs-2.4.log)

**Comment by driesmp** [comment]
I guess specifying an "include dir" in the Makefile could work.

**Comment by tavianator** [comment]
So a while ago I read through https://wiki.freebsd.org/WarnerLosh/UsrLocal and https://reviews.freebsd.org/V6 and my impression was that when building ports, `/usr/local/{include,lib}` were added to the search paths automatically.  Is that not the case?

If you need to add them explicitly, you can do

```
$ gmake EXTRA_CPPFLAGS="-I/usr/local/include" EXTRA_LDFLAGS="-L/usr/local/lib"
```

or set those variables in the environment.

**Comment by tavianator** [comment]
Actually on second thought, I will fix this automatically by invoking `onig-config`.  That way local development on FreeBSD is much less painful

**Comment by driesmp** [comment]
Fix works great thanks.

**Comment by yermulnik** [comment]
Can https://github.com/tavianator/bfs/issues/93 be related or is this an local to me issue?
