### ISSUE TITLE
Packaging for Fedora

### ISSUE THREAD

**Issue by chapmanjacobd** [tavianator/bfs#83]
I'm sure the process for getting a package in fedora repos is somewhat annoying but I see that there are many common platforms already supported and the addition of Fedora would be welcome 

https://copr.fedorainfracloud.org/

**Comment by chapmanjacobd** [comment]
To build it I had to install these deps

```
sudo dnf install oniguruma-devel libacl-devel libattr-devel libcap-devel
```

**Comment by tavianator** [comment]
> I'm sure the process for getting a package in fedora repos is somewhat annoying but I see that there are many common platforms already supported and the addition of Fedora would be welcome

I agree, I'd love if someone would package bfs for Fedora.  Not sure it should be me though, I don't use it and wouldn't necessarily notice problems.  I would help out if someone else packaged it thought!

> To build it I had to install these deps
>
>     sudo dnf install oniguruma-devel libacl-devel libattr-devel libcap-devel

Good to know.  That should be added to the README, do you want to make a PR?

> although I have to say that was the quickest compiling process I've ever had to do

Glad to hear it :)

**Comment by xfgusta** [comment]
Hi, I'm a Fedora packager. I have already created a package for bfs and submitted it for an official review. It may take time for someone to review and approve it. Meanwhile, I'm maintaining a Copr project as suggested by @chapmanjacobd.

To install `bfs` from the Copr repo:

```ascii
dnf copr enable xfgusta/bfs
dnf install bfs
```

The Copr package follows the Fedora packaging guidelines.

https://bugzilla.redhat.com/show_bug.cgi?id=2087264
https://copr.fedorainfracloud.org/coprs/xfgusta/bfs

**Comment by tavianator** [comment]
@xfgusta Thank you!  Do you think it makes sense to add those instructions to https://github.com/tavianator/bfs#installation, at least until there's an official package?

**Comment by xfgusta** [comment]
> @xfgusta Thank you! Do you think it makes sense to add those instructions to https://github.com/tavianator/bfs#installation, at least until there's an official package?

It makes sense to me. I will let you know when there is an official package.

**Comment by xfgusta** [comment]
Quick update: #95
