### ISSUE TITLE
Building for aarch

### ISSUE THREAD

**Issue by edshamis** [tavianator/bfs#96]
I'm trying to build from Termux on Android bad get this
```
src/pwcache.c:52:18: error: incompatible integer to pointer conversion initializing 'struct passwd *' with an expression of type 'int' [-Wint-conversion]
                struct passwd *ent = getpwent();
```

uname -a
```
Linux localhost 4.14.180-perf-ge2a1322887a5 #1 SMP PREEMPT Mon Mar 28 19:47:44 CST 2022 aarch64 Android
```
Any help would be appreciated

**Comment by tavianator** [comment]
eb47b3c51ad7e321563d70ff142f47cedf8830bc fixes the Android build for API level 26.  The tests don't run yet because SELinux blocks hard links on recent Android versions.
